"""empty message

Revision ID: 06ba91ad06cc
Revises: 
Create Date: 2021-02-18 12:29:11.356438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ba91ad06cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rec_left', sa.Integer(), nullable=False),
    sa.Column('rec_top', sa.Integer(), nullable=False),
    sa.Column('rec_right', sa.Integer(), nullable=False),
    sa.Column('rec_bottom', sa.Integer(), nullable=False),
    sa.Column('face_points', sa.String(), nullable=False),
    sa.Column('descriptor', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_info')
    # ### end Alembic commands ###
